.PHONY: all build clean

build:
	GO111MODULE=auto GOBIN=${PWD}/built-lambda GO_IMPORT_PATH=src/lambda go get ./...
	GOOS=linux GOARCH=amd64 GO111MODULE=auto GOBIN=${PWD}/built-lambda GO_IMPORT_PATH=src/lambda go install -ldflags "-X main.secretJWTKey=$$JWT_SECRET_KEY -X main.mongoDBPassword=$$MONGODB_PASSWORD" ./...
